### ISSUE TITLE
Is it possible to skip system headers? 

### ISSUE THREAD

**Issue by ashishbijlani** [joliebig/Hercules#3]
Is it possible to skip system headers while refactoring?

**Comment by joliebig** [comment]
I'm not sure I understand Your question correctly. No refactorings will be performed for files, that the refactoring process does not have write-access to. See the _isWritable_ premise in the corresponding  [paper](http://www.infosun.fim.uni-passau.de/publications/docs/LiJaGa+15.pdf#page=7).

**Comment by ashishbijlani** [comment]
I saw that ifdef to if refactoring is being done for included system headers as well. For example, if stdio.h is included in test.c, then "ifdeftoif.sh test.c" will emit code that includes preprocessing directives (#ifdef, etc) from stdio.h as well? Is it possible to not include directives from system headers?

**Comment by joliebig** [comment]
There is no option to limit the `#ifdef` to `if` transformation to source files.

**Comment by ashishbijlani** [comment]
Thanks!
